### ISSUE TITLE
Smarty 3 and Codeigniter 3

### ISSUE THREAD

**Issue by Jagarm** [AkenRoberts/CodeIgniter_Smarty#2]
I love the way you integrated smarty into CodeIgniter and was wondering if you will be providing instructions to integrate Smarty 3 into Codeigniter 3.

There are many tutorials and few of them do not work well.

Thank you

**Comment by AkenRoberts** [comment]
Hi @Jagarm. Thanks for your interest in this library.

I'll see if I can take some time and check out this lib's compatibility with CodeIgniter 3. I don't recall CI3 changing anything fundamentally with libraries or views, so there should be relatively little work involved with incorporating these changes into a CI3 app.

No promises on timeline, but I will do my best. :)

**Comment by AkenRoberts** [comment]
You might be interested in this library, also: https://github.com/Vheissu/Ci-Smarty  It appears to be more actively maintained and has a higher user base. It doesn't reuse CI's built in view syntax like mine does (which is actually why I wrote this one in the first place), but it may help you get Smarty integrated.

**Comment by Jagarm** [comment]
Thank you Cryode, I will look at that library. You are using the CI's built in view syntax and that's why i like your library.

I understand you are busy but do let me know if you get around it

Regards

**Comment by Jagarm** [comment]
I copied the files to CI 3 and works like a charm.

I got some php notices but that was because the variables weren't define.

It is working very well and I love it

Thanks for your hard work
